export const ScreenConstants = {
    TFS_HEADING: 'Welcome to Trade Fantasy Game',
    SELECT_ROUND: 'Please Select Round to Schedule the match:',
    NEXT: 'Next',
    SELECT_TEAM_A: 'Select Team A',
    SELECT_TEAM_B: 'Select Team B',
    TOURNAMENT_TEAMS: 'Tournament Teams',
    SCHEDULE_MATCH: 'Schedule Match',
    MATCH_SCHEDULED: 'Match has been scheduled!',
    AVAILABLE_TIME_SLOTS: 'Available Time Slots',
    SCHEDULED_MATCHES: 'Scheduled Matches',
    MATCH_SCHEDULED_ON: 'Match Scheduled on',
    UPCOMING: 'UPCOMING',
    DELETE_ALERT: 'Are you sure you want to delete match?',
    CANCEL: 'Cancel',
    DELETE: 'Delete',
}